name: Deploy to Vercel

on:
  push:
    branches: [main]
    paths:
      - 'fleeks-clean/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        run: |
          echo "Triggering Vercel deployment..."
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }})
          
          if [ $response -eq 201 ]; then
            echo "✅ Deployment triggered successfully!"
          else
            echo "❌ Failed to trigger deployment. Response code: $response"
            exit 1
          fi
      
      - name: Wait for deployment
        run: |
          echo "Waiting 30 seconds for deployment to start..."
          sleep 30
          echo "Check deployment status at: https://vercel.com/dashboard"